/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package knjiznica_Galic_4e;

import javax.swing.JOptionPane;

/**
 *
 * @author Galic
 */
public class Glavna extends javax.swing.JFrame {

    /**
     * Creates new form Glavna
     */
    public Glavna() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        naslov_Glavna_JLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        posudba_Glavna_jButton = new javax.swing.JButton();
        povrat_Glavna_jButton = new javax.swing.JButton();
        statistika_Glavna_jButton = new javax.swing.JButton();
        upisNoveKnjige_Glavna_jButton = new javax.swing.JButton();
        upisNovogUcenika_Glavna_jButton = new javax.swing.JButton();
        povrat_Glavna_jLabel = new javax.swing.JLabel();
        posudba_Glavna_jLabel = new javax.swing.JLabel();
        statistika_Glavna_jLabel = new javax.swing.JLabel();
        upisNoveKnjige_Glavna_jLabel = new javax.swing.JLabel();
        upisNovogUcenika_Glavna_jLabel = new javax.swing.JLabel();
        odjava_Glavna_jButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);

        naslov_Glavna_JLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        naslov_Glavna_JLabel.setForeground(new java.awt.Color(0, 0, 255));
        naslov_Glavna_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        naslov_Glavna_JLabel.setText("Dobrodošli u knjižnicu ETŠ");
        naslov_Glavna_JLabel.setToolTipText("");
        naslov_Glavna_JLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        naslov_Glavna_JLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/knjiznica_Galic_4e/ets_logo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        posudba_Glavna_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/knjiznica_Galic_4e/posudba.png"))); // NOI18N
        posudba_Glavna_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posudba_Glavna_jButtonActionPerformed(evt);
            }
        });

        povrat_Glavna_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/knjiznica_Galic_4e/povrat.png"))); // NOI18N
        povrat_Glavna_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                povrat_Glavna_jButtonActionPerformed(evt);
            }
        });

        statistika_Glavna_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/knjiznica_Galic_4e/statistika.png"))); // NOI18N
        statistika_Glavna_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statistika_Glavna_jButtonActionPerformed(evt);
            }
        });

        upisNoveKnjige_Glavna_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/knjiznica_Galic_4e/upisNoveKnjige.png"))); // NOI18N
        upisNoveKnjige_Glavna_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upisNoveKnjige_Glavna_jButtonActionPerformed(evt);
            }
        });

        upisNovogUcenika_Glavna_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/knjiznica_Galic_4e/upisNovogUcenika.jpg"))); // NOI18N
        upisNovogUcenika_Glavna_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upisNovogUcenika_Glavna_jButtonActionPerformed(evt);
            }
        });

        povrat_Glavna_jLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        povrat_Glavna_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        povrat_Glavna_jLabel.setText("Povrat");
        povrat_Glavna_jLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        povrat_Glavna_jLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        posudba_Glavna_jLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        posudba_Glavna_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        posudba_Glavna_jLabel.setText("Posudba");
        posudba_Glavna_jLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        posudba_Glavna_jLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        statistika_Glavna_jLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        statistika_Glavna_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statistika_Glavna_jLabel.setText("Statistika");
        statistika_Glavna_jLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        statistika_Glavna_jLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        upisNoveKnjige_Glavna_jLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        upisNoveKnjige_Glavna_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        upisNoveKnjige_Glavna_jLabel.setText("Upis nove knjige");
        upisNoveKnjige_Glavna_jLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        upisNoveKnjige_Glavna_jLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        upisNovogUcenika_Glavna_jLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        upisNovogUcenika_Glavna_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        upisNovogUcenika_Glavna_jLabel.setText("Upis novog učenika");
        upisNovogUcenika_Glavna_jLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        upisNovogUcenika_Glavna_jLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        odjava_Glavna_jButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        odjava_Glavna_jButton.setForeground(new java.awt.Color(51, 51, 255));
        odjava_Glavna_jButton.setText("Odjava");
        odjava_Glavna_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odjava_Glavna_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(naslov_Glavna_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(posudba_Glavna_jButton)
                            .addComponent(posudba_Glavna_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(povrat_Glavna_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(povrat_Glavna_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(statistika_Glavna_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(statistika_Glavna_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(upisNoveKnjige_Glavna_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(upisNoveKnjige_Glavna_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(odjava_Glavna_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(upisNovogUcenika_Glavna_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(upisNovogUcenika_Glavna_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(naslov_Glavna_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(posudba_Glavna_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(povrat_Glavna_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(povrat_Glavna_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posudba_Glavna_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(upisNovogUcenika_Glavna_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(upisNoveKnjige_Glavna_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statistika_Glavna_jButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upisNoveKnjige_Glavna_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(statistika_Glavna_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(upisNovogUcenika_Glavna_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addComponent(odjava_Glavna_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void upisNovogUcenika_Glavna_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upisNovogUcenika_Glavna_jButtonActionPerformed
        setVisible(false);
        new NoviUcenik().setVisible(true);
    }//GEN-LAST:event_upisNovogUcenika_Glavna_jButtonActionPerformed

    private void upisNoveKnjige_Glavna_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upisNoveKnjige_Glavna_jButtonActionPerformed
        setVisible(false);
        new NovaKnjiga().setVisible(true);
    }//GEN-LAST:event_upisNoveKnjige_Glavna_jButtonActionPerformed

    private void posudba_Glavna_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posudba_Glavna_jButtonActionPerformed
        setVisible(false);
        new Posudba().setVisible(true);
    }//GEN-LAST:event_posudba_Glavna_jButtonActionPerformed

    private void odjava_Glavna_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odjava_Glavna_jButtonActionPerformed
        //gumb za odjavu
        JOptionPane.showMessageDialog(null, "Uspješno ste odjavljeni!", "ODJAVA", JOptionPane.INFORMATION_MESSAGE); 
        System.exit(0);
    }//GEN-LAST:event_odjava_Glavna_jButtonActionPerformed

    private void povrat_Glavna_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_povrat_Glavna_jButtonActionPerformed
        setVisible(false);
        new Povrat().setVisible(true);
    }//GEN-LAST:event_povrat_Glavna_jButtonActionPerformed

    private void statistika_Glavna_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statistika_Glavna_jButtonActionPerformed
        setVisible(false);
        new Statistika().setVisible(true);
    }//GEN-LAST:event_statistika_Glavna_jButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Glavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Glavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Glavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Glavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Glavna().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel naslov_Glavna_JLabel;
    private javax.swing.JButton odjava_Glavna_jButton;
    private javax.swing.JButton posudba_Glavna_jButton;
    private javax.swing.JLabel posudba_Glavna_jLabel;
    private javax.swing.JButton povrat_Glavna_jButton;
    private javax.swing.JLabel povrat_Glavna_jLabel;
    private javax.swing.JButton statistika_Glavna_jButton;
    private javax.swing.JLabel statistika_Glavna_jLabel;
    private javax.swing.JButton upisNoveKnjige_Glavna_jButton;
    private javax.swing.JLabel upisNoveKnjige_Glavna_jLabel;
    private javax.swing.JButton upisNovogUcenika_Glavna_jButton;
    private javax.swing.JLabel upisNovogUcenika_Glavna_jLabel;
    // End of variables declaration//GEN-END:variables
}
