/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package knjiznica_Galic_4e;

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Galic
 */
public class NoviUcenik extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement pst;
    
    public NoviUcenik() {
        initComponents();
        conn = JavaConnect.connectDB();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        naslov_noviUcenik_JLabel = new javax.swing.JLabel();
        IDUcenika_noviUcenik_JLabel = new javax.swing.JLabel();
        imeUcenika_noviUcenik_JLabel = new javax.swing.JLabel();
        prezimeUcenika_noviUcenik_JLabel = new javax.swing.JLabel();
        razred_noviUcenik_JLabel = new javax.swing.JLabel();
        IDUcenika_noviUcenik_JTextField = new javax.swing.JTextField();
        imeUcenika_noviUcenik_JTextField = new javax.swing.JTextField();
        prezimeUcenika_noviUcenik_JTextField = new javax.swing.JTextField();
        razred_noviUcenik_JTextField = new javax.swing.JTextField();
        spremi_noviUcenik_JButton = new javax.swing.JButton();
        natrag_noviUcenik_JButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        naslov_noviUcenik_JLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        naslov_noviUcenik_JLabel.setForeground(new java.awt.Color(0, 0, 255));
        naslov_noviUcenik_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        naslov_noviUcenik_JLabel.setText("Novi učenik");
        naslov_noviUcenik_JLabel.setToolTipText("");
        naslov_noviUcenik_JLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        naslov_noviUcenik_JLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        IDUcenika_noviUcenik_JLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IDUcenika_noviUcenik_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IDUcenika_noviUcenik_JLabel.setText("ID učenika");

        imeUcenika_noviUcenik_JLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        imeUcenika_noviUcenik_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imeUcenika_noviUcenik_JLabel.setText("Ime učenika");

        prezimeUcenika_noviUcenik_JLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        prezimeUcenika_noviUcenik_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prezimeUcenika_noviUcenik_JLabel.setText("Prezime učenika");

        razred_noviUcenik_JLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        razred_noviUcenik_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        razred_noviUcenik_JLabel.setText("Razred");

        IDUcenika_noviUcenik_JTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IDUcenika_noviUcenik_JTextField.setToolTipText("");

        imeUcenika_noviUcenik_JTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        imeUcenika_noviUcenik_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imeUcenika_noviUcenik_JTextFieldActionPerformed(evt);
            }
        });

        prezimeUcenika_noviUcenik_JTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        razred_noviUcenik_JTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        spremi_noviUcenik_JButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        spremi_noviUcenik_JButton.setText("Spremi");
        spremi_noviUcenik_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spremi_noviUcenik_JButtonActionPerformed(evt);
            }
        });

        natrag_noviUcenik_JButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        natrag_noviUcenik_JButton.setText("Natrag");
        natrag_noviUcenik_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                natrag_noviUcenik_JButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(naslov_noviUcenik_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(prezimeUcenika_noviUcenik_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(imeUcenika_noviUcenik_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IDUcenika_noviUcenik_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(razred_noviUcenik_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IDUcenika_noviUcenik_JTextField)
                            .addComponent(imeUcenika_noviUcenik_JTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(prezimeUcenika_noviUcenik_JTextField)
                            .addComponent(razred_noviUcenik_JTextField))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spremi_noviUcenik_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(natrag_noviUcenik_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(naslov_noviUcenik_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDUcenika_noviUcenik_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDUcenika_noviUcenik_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imeUcenika_noviUcenik_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imeUcenika_noviUcenik_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prezimeUcenika_noviUcenik_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prezimeUcenika_noviUcenik_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(razred_noviUcenik_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(razred_noviUcenik_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spremi_noviUcenik_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(natrag_noviUcenik_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imeUcenika_noviUcenik_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imeUcenika_noviUcenik_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imeUcenika_noviUcenik_JTextFieldActionPerformed

    private void spremi_noviUcenik_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spremi_noviUcenik_JButtonActionPerformed
        
        if(IDUcenika_noviUcenik_JTextField.getText().isEmpty() || imeUcenika_noviUcenik_JTextField.getText().isEmpty() ||
           prezimeUcenika_noviUcenik_JTextField.getText().isEmpty() || razred_noviUcenik_JTextField.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "Morate ispuniti sva polja!");
        }
        
        else{
        //upisivanje unešenih podataka za novog učenika u bazu
        try{
            //SQL upit
            String sql = "INSERT INTO ucenik (ID_ucenik, ime_ucenik, prezime_ucenik, razred_ucenik, brPosudbi_ucenik) VALUES (?, ?, ?, ?, ?)";
            pst = conn.prepareStatement(sql);
            
            //postavljanje podataka kojih smo upisali u textFields u bazu na njihova predviđena mjesta
            pst.setString(1, IDUcenika_noviUcenik_JTextField.getText());
            pst.setString(2, imeUcenika_noviUcenik_JTextField.getText());
            pst.setString(3, prezimeUcenika_noviUcenik_JTextField.getText());
            pst.setString(4, razred_noviUcenik_JTextField.getText());
            pst.setString(5, "0");
            
            pst.execute();
            pst.close();
            
            JOptionPane.showMessageDialog(null, "Novi učenik uspješno upisan u knjižnicu!");
            
            conn.close();
            
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
      }
    }//GEN-LAST:event_spremi_noviUcenik_JButtonActionPerformed

    private void natrag_noviUcenik_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_natrag_noviUcenik_JButtonActionPerformed
        setVisible(false);
        new Glavna().setVisible(true);
    }//GEN-LAST:event_natrag_noviUcenik_JButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NoviUcenik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NoviUcenik().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDUcenika_noviUcenik_JLabel;
    private javax.swing.JTextField IDUcenika_noviUcenik_JTextField;
    private javax.swing.JLabel imeUcenika_noviUcenik_JLabel;
    private javax.swing.JTextField imeUcenika_noviUcenik_JTextField;
    private javax.swing.JLabel naslov_noviUcenik_JLabel;
    private javax.swing.JButton natrag_noviUcenik_JButton;
    private javax.swing.JLabel prezimeUcenika_noviUcenik_JLabel;
    private javax.swing.JTextField prezimeUcenika_noviUcenik_JTextField;
    private javax.swing.JLabel razred_noviUcenik_JLabel;
    private javax.swing.JTextField razred_noviUcenik_JTextField;
    private javax.swing.JButton spremi_noviUcenik_JButton;
    // End of variables declaration//GEN-END:variables
}
