/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package knjiznica_Galic_4e;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Galic
 */
public class Prijava extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    
    /**
     * Creates new form Prijava
     */
    public Prijava() {
        initComponents();
        conn = JavaConnect.connectDB();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        korisnicko_ime_prijava_JLabel = new javax.swing.JLabel();
        lozinka_prijava_JLabel = new javax.swing.JLabel();
        korisnicko_ime_prijava_JTextField = new javax.swing.JTextField();
        lozinka_prijava_JPasswordField = new javax.swing.JPasswordField();
        prijava_JButton = new javax.swing.JButton();
        registracija_JButton = new javax.swing.JButton();
        zaboravljena_lozinka_JButton = new javax.swing.JButton();
        naslov_prijava_jLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        korisnicko_ime_prijava_JLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        korisnicko_ime_prijava_JLabel.setText("Korisničko ime");

        lozinka_prijava_JLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lozinka_prijava_JLabel.setText("Lozinka");

        korisnicko_ime_prijava_JTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lozinka_prijava_JPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        prijava_JButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        prijava_JButton.setText("Prijava");
        prijava_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prijava_JButtonActionPerformed(evt);
            }
        });

        registracija_JButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        registracija_JButton.setText("Registracija");
        registracija_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registracija_JButtonActionPerformed(evt);
            }
        });

        zaboravljena_lozinka_JButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zaboravljena_lozinka_JButton.setText("Zaboravljena lozinka?");
        zaboravljena_lozinka_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zaboravljena_lozinka_JButtonActionPerformed(evt);
            }
        });

        naslov_prijava_jLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        naslov_prijava_jLabel.setForeground(new java.awt.Color(0, 0, 255));
        naslov_prijava_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        naslov_prijava_jLabel.setText("Prijava");
        naslov_prijava_jLabel.setToolTipText("");
        naslov_prijava_jLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        naslov_prijava_jLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(prijava_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addGap(71, 71, 71)
                .addComponent(registracija_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(korisnicko_ime_prijava_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lozinka_prijava_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(korisnicko_ime_prijava_JTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(lozinka_prijava_JPasswordField))
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(naslov_prijava_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(zaboravljena_lozinka_JButton)
                        .addGap(112, 112, 112))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(naslov_prijava_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(korisnicko_ime_prijava_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(korisnicko_ime_prijava_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lozinka_prijava_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lozinka_prijava_JPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(registracija_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prijava_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(zaboravljena_lozinka_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registracija_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registracija_JButtonActionPerformed
        new Registracija().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_registracija_JButtonActionPerformed

    private void prijava_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prijava_JButtonActionPerformed
        
        String korisnicko_ime = korisnicko_ime_prijava_JTextField.getText();
        String lozinka = lozinka_prijava_JPasswordField.getText();
        
        //SQL upit
        String sql = "SELECT * FROM korisnik WHERE username_korisnik = '" + korisnicko_ime + "'";
        
        //prijava u knjižnicu
        try{
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            //ako postoji uneseno korisničko ime, pusti dalje kod
            if(rs.next()){                
                String lozinka_iz_baze = rs.getString(4);
                
                //ako je lozinka tog korisnika točno unesena, uđi u glavna.java, ako ne, onda baci obavijest da je lozinka kriva
                if(lozinka.equals(lozinka_iz_baze)){
                    new Glavna().setVisible(true);
                    this.setVisible(false);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Lozinka nije točna!\nPokušajte ponovo!");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Netočan username!\nPokušajte ponovo!");
            }
            
            conn.close();
            
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_prijava_JButtonActionPerformed

    private void zaboravljena_lozinka_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zaboravljena_lozinka_JButtonActionPerformed
        new ZaboravljenaLozinka().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_zaboravljena_lozinka_JButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prijava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prijava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prijava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prijava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Prijava().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel korisnicko_ime_prijava_JLabel;
    private javax.swing.JTextField korisnicko_ime_prijava_JTextField;
    private javax.swing.JLabel lozinka_prijava_JLabel;
    private javax.swing.JPasswordField lozinka_prijava_JPasswordField;
    private javax.swing.JLabel naslov_prijava_jLabel;
    private javax.swing.JButton prijava_JButton;
    private javax.swing.JButton registracija_JButton;
    private javax.swing.JButton zaboravljena_lozinka_JButton;
    // End of variables declaration//GEN-END:variables
}
