/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package knjiznica_Galic_4e;

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Galic
 */
public class Registracija extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement pst;
    
    public Registracija() {
        initComponents();
        conn = JavaConnect.connectDB();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    
    public void provjeraSigurnostiLozinke() {
        String lozinka = lozinka_registracija_JPasswordField.getText();   
        
        boolean uppercase = false;
        boolean lowercase = false;
        boolean specialcharacters = false;
        boolean digits = false;
        
        char[] Password = lozinka.toCharArray();
        
        for(int i = 0; i < lozinka.length(); i++){
            
            if(Character.isUpperCase(Password[i]))
                uppercase = true;
            
            if(Character.isLowerCase(Password[i]))
                lowercase = true;
            
            if(Character.isDigit(Password[i]))
                digits = true;
            
            if(lozinka.contains("~") || lozinka.contains("!") || lozinka.contains("@") ||
               lozinka.contains("#") || lozinka.contains("$") || lozinka.contains("%") ||
               lozinka.contains("^") || lozinka.contains("&") || lozinka.contains("*") ||
               lozinka.contains("+") || lozinka.contains("-") || lozinka.contains("/") ||
               lozinka.contains("(") || lozinka.contains(")") || lozinka.contains("<") ||
                    lozinka.contains(">"))
                specialcharacters = true;
                 
        }
        
        if(lozinka.length() < 6){
            JOptionPane.showMessageDialog(null, "Vaša lozinka je pre kratka!\nMora imati barem 6 znakova!", "Sigurnost lozinke", JOptionPane.INFORMATION_MESSAGE);
            return;
        }  
        if(lozinka.length() >= 6 && uppercase && lowercase && digits && specialcharacters){
            JOptionPane.showMessageDialog(null, "Vaša lozinka je jaka!", "Sigurnost lozinke", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        if ((lozinka.length() >= 6 && ((uppercase && lowercase) || digits && specialcharacters))
            &&
            (lozinka.length() >= 6 && ((uppercase && lowercase) && digits || specialcharacters))){
            JOptionPane.showMessageDialog(null, "Vaša lozinka je osrednja!\nMožete ju probati jos ojačati!", "Sigurnost lozinke", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        if(lozinka.length() >= 6 && (uppercase || lowercase || digits || specialcharacters)){
            JOptionPane.showMessageDialog(null, "Vaša lozinka je slaba!\nBilo bi dobro da ju promijenite da bude jača!", "Sigurnost lozinke", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        naslov_registracija_jLabel = new javax.swing.JLabel();
        ime_registracija_JLabel = new javax.swing.JLabel();
        prezime_registracija_JLabel = new javax.swing.JLabel();
        korisnicko_ime_registracija_JLabel = new javax.swing.JLabel();
        lozinka_registracija_JLabel = new javax.swing.JLabel();
        pitanje_registracija_JLabel = new javax.swing.JLabel();
        odgovor_registracija_JLabel = new javax.swing.JLabel();
        ime_registracija_JTextField = new javax.swing.JTextField();
        prezime_registracija_JTextField = new javax.swing.JTextField();
        korisnicko_ime_registracija_JTextField = new javax.swing.JTextField();
        lozinka_registracija_JPasswordField = new javax.swing.JPasswordField();
        odgovor_registracija_JTextField = new javax.swing.JTextField();
        pitanje_JComboBox = new javax.swing.JComboBox<>();
        stvori_registracija_JButton = new javax.swing.JButton();
        natrag_registracija_JButton = new javax.swing.JButton();
        provjeraLozinke_registracija_JButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        naslov_registracija_jLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        naslov_registracija_jLabel.setForeground(new java.awt.Color(0, 0, 255));
        naslov_registracija_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        naslov_registracija_jLabel.setText("Registracija novog korisnika");
        naslov_registracija_jLabel.setToolTipText("");
        naslov_registracija_jLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        naslov_registracija_jLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ime_registracija_JLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ime_registracija_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ime_registracija_JLabel.setText("Ime");

        prezime_registracija_JLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        prezime_registracija_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prezime_registracija_JLabel.setText("Prezime");

        korisnicko_ime_registracija_JLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        korisnicko_ime_registracija_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        korisnicko_ime_registracija_JLabel.setText("Korisničko ime");

        lozinka_registracija_JLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lozinka_registracija_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lozinka_registracija_JLabel.setText("Lozinka");

        pitanje_registracija_JLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pitanje_registracija_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pitanje_registracija_JLabel.setText("Sigurnosno pitanje");

        odgovor_registracija_JLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        odgovor_registracija_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        odgovor_registracija_JLabel.setText("Odgovor");

        ime_registracija_JTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        prezime_registracija_JTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        prezime_registracija_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prezime_registracija_JTextFieldActionPerformed(evt);
            }
        });

        korisnicko_ime_registracija_JTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        korisnicko_ime_registracija_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                korisnicko_ime_registracija_JTextFieldActionPerformed(evt);
            }
        });

        lozinka_registracija_JPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lozinka_registracija_JPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lozinka_registracija_JPasswordFieldActionPerformed(evt);
            }
        });

        odgovor_registracija_JTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pitanje_JComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pitanje_JComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kako ti se zove kućni ljubimac?", "Koliko godina ti ima brat?", "U kojem kvartu živiš?", "Kako ti se zove najbolji prijatelj?" }));

        stvori_registracija_JButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        stvori_registracija_JButton.setText("Stvori");
        stvori_registracija_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stvori_registracija_JButtonActionPerformed(evt);
            }
        });

        natrag_registracija_JButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        natrag_registracija_JButton.setText("Natrag");
        natrag_registracija_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                natrag_registracija_JButtonActionPerformed(evt);
            }
        });

        provjeraLozinke_registracija_JButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        provjeraLozinke_registracija_JButton.setText("Provjeri sigurnost lozinke");
        provjeraLozinke_registracija_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provjeraLozinke_registracija_JButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pitanje_registracija_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(odgovor_registracija_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(odgovor_registracija_JTextField)
                            .addComponent(pitanje_JComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(stvori_registracija_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(natrag_registracija_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(naslov_registracija_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(ime_registracija_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(korisnicko_ime_registracija_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lozinka_registracija_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(prezime_registracija_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(provjeraLozinke_registracija_JButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(ime_registracija_JTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(prezime_registracija_JTextField)
                            .addComponent(korisnicko_ime_registracija_JTextField)
                            .addComponent(lozinka_registracija_JPasswordField))))
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(naslov_registracija_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(ime_registracija_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(prezime_registracija_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(korisnicko_ime_registracija_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(lozinka_registracija_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ime_registracija_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(prezime_registracija_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(korisnicko_ime_registracija_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(lozinka_registracija_JPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(provjeraLozinke_registracija_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pitanje_JComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pitanje_registracija_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(odgovor_registracija_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(odgovor_registracija_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(natrag_registracija_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stvori_registracija_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prezime_registracija_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prezime_registracija_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prezime_registracija_JTextFieldActionPerformed

    private void korisnicko_ime_registracija_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_korisnicko_ime_registracija_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_korisnicko_ime_registracija_JTextFieldActionPerformed

    private void natrag_registracija_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_natrag_registracija_JButtonActionPerformed
        setVisible(false);
        new Prijava().setVisible(true);
    }//GEN-LAST:event_natrag_registracija_JButtonActionPerformed

    private void stvori_registracija_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stvori_registracija_JButtonActionPerformed

        if(korisnicko_ime_registracija_JTextField.getText().isEmpty() || ime_registracija_JTextField.getText().isEmpty() ||
           prezime_registracija_JTextField.getText().isEmpty() || lozinka_registracija_JPasswordField.getText().isEmpty() ||
           odgovor_registracija_JTextField.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "Morate ispuniti sva polja!");   
        }
        
        else{
        
        //stvaranje novog računa
        try{
            //SQL upit
            String sql = "INSERT INTO korisnik (username_korisnik, ime_korisnik, prezime_korisnik, lozinka_korisnik, pitanje_korisnik, odgovor_korisnik) VALUES (?, ?, ?, ?, ?, ?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1, korisnicko_ime_registracija_JTextField.getText());
            pst.setString(2, ime_registracija_JTextField.getText());
            pst.setString(3, prezime_registracija_JTextField.getText());
            pst.setString(4, lozinka_registracija_JPasswordField.getText());
            pst.setString(5, (String) pitanje_JComboBox.getSelectedItem());
            pst.setString(6, odgovor_registracija_JTextField.getText());
            
            pst.execute();
            pst.close();
            
            JOptionPane.showMessageDialog(null, "Novi korisnički račun uspješno stvoren!");
            
            conn.close();
            
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
      }
    }//GEN-LAST:event_stvori_registracija_JButtonActionPerformed

    private void lozinka_registracija_JPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lozinka_registracija_JPasswordFieldActionPerformed
     
    }//GEN-LAST:event_lozinka_registracija_JPasswordFieldActionPerformed

    private void provjeraLozinke_registracija_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provjeraLozinke_registracija_JButtonActionPerformed
        provjeraSigurnostiLozinke();
    }//GEN-LAST:event_provjeraLozinke_registracija_JButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Registracija().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ime_registracija_JLabel;
    private javax.swing.JTextField ime_registracija_JTextField;
    private javax.swing.JLabel korisnicko_ime_registracija_JLabel;
    private javax.swing.JTextField korisnicko_ime_registracija_JTextField;
    private javax.swing.JLabel lozinka_registracija_JLabel;
    private javax.swing.JPasswordField lozinka_registracija_JPasswordField;
    private javax.swing.JLabel naslov_registracija_jLabel;
    private javax.swing.JButton natrag_registracija_JButton;
    private javax.swing.JLabel odgovor_registracija_JLabel;
    private javax.swing.JTextField odgovor_registracija_JTextField;
    private javax.swing.JComboBox<String> pitanje_JComboBox;
    private javax.swing.JLabel pitanje_registracija_JLabel;
    private javax.swing.JLabel prezime_registracija_JLabel;
    private javax.swing.JTextField prezime_registracija_JTextField;
    private javax.swing.JButton provjeraLozinke_registracija_JButton;
    private javax.swing.JButton stvori_registracija_JButton;
    // End of variables declaration//GEN-END:variables

}
